### ISSUE TITLE
Solution for not overlapping content

### ISSUE THREAD

**Issue by gjm** [wire-elements/wire-spy#14]
Right now, when the wire-spy popup opens, it overlaps content on the bottom which may itself contain components we want to analyze. It would be nice to have some solution for this problem.

**Comment by PhiloNL** [comment]
Thanks for reporting! This is now fixed https://github.com/wire-elements/wire-spy/commit/f7b2b843b611e8f7dd757c2dadec9becf5bb383b

**Comment by gjm** [comment]
@PhiloNL the issue i still present for me...
