### ISSUE TITLE
WireSpy is loaded when it shouldn't

### ISSUE THREAD

**Issue by aerni** [wire-elements/wire-spy#2]
I installed WireSpy in a project that uses Statamic. The autoinjection of WireSpy's assets works as expected on the frontend. However, in the Statamic control panel, WireSpy's assets are injected as well. Despite the fact, that Livewire isn't used in the control panel. This leaves a broken WireSpy debug bar.

![CleanShot 2024-10-09 at 10 18 45@2x](https://github.com/user-attachments/assets/21d011cd-4f7d-4fae-b0f8-6ccc8cafffa0)

I fiddled around and changing this boolean to `false` fixes the issue:
https://github.com/wire-elements/wire-spy/blob/482ecff8e96fde7f831a0258e6d7671470d1742e/src/SupportAutoInjectedAssets.php#L64

I didn't notice this change breaking anything else.

**Comment by PhiloNL** [comment]
Thanks @aerni 👍  Fixed and tagged: https://github.com/wire-elements/wire-spy/commit/ff62e1a5e7ab74aacc8cba57cee33ea8db129d8e
